### ISSUE TITLE
couple improvements to settings page

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#10]
1. most of the tab/page has dark theme support like the subtitle, audio config, source browser; but the settings page doesn't support it currently as you can see in the below screenshots.

2. second one is that if you see the screenshot no. 1, the close (red) button is little offset and not perfect. it would nice to it fixed. although the other page like source browser has it, since the settings page is separated with the title bar and is two-toned, this can be easily visible. (also a little bigger (like couple px extra) would also nice.)

#### Screenshot

1. within player

![vivaldi_7WVwU6ziWY](https://github.com/Andrews54757/FastStream/assets/96393348/f9388575-ca99-4b5a-b110-d34498687549)

4. within extension page

![vivaldi_YhKs5Z9Wh2](https://github.com/Andrews54757/FastStream/assets/96393348/204bcd05-f8aa-4675-a04e-e4bd3af9bb39)

**Comment by Andrews54757** [comment]
The settings page was created quickly to just have something that works. It will be redone entirely in a future update.

**Comment by Andrews54757** [comment]
I've made the close buttons bigger for version 1.2.0. Alignment issue may still be present however, this will require some HTML/CSS refactoring. Still on the TODO list.

You can also close windows by pressing ESC (in 1.2.0) or by clicking the video (any version).

**Comment by Rusenche** [comment]
I didn't see an option where I could:
1. Stop youtube autoplay?
2. Set the highest possible resolution wherever there are clips that allow for example 1080p? At the moment I do not find such an option and in most places it is strange that it plays an intermediate resolution, and not the highest possible for the source.

**Comment by Rusenche** [comment]
I didn't see an option where I could:
1. Stop youtube autoplay?
2. Set the highest possible resolution wherever there are clips that allow for example 1080p? At the moment I do not find such an option and in most places it is strange that it plays an intermediate resolution, and not the highest possible for the source.

I didn't find any information - if any video contains ads - does this app skip them?

**Comment by Andrews54757** [comment]
@Rusenche autoplay and initial quality options are added and will be available in V1.2.9 https://github.com/Andrews54757/FastStream/commit/c808414d30ae2575620b66c19e644899e289c9ee

This player won't play ads on Youtube.

**Comment by Rusenche** [comment]
> @Rusenche autoplay and initial quality options are added and will be available in V1.2.9 [c808414](https://github.com/Andrews54757/FastStream/commit/c808414d30ae2575620b66c19e644899e289c9ee)
> 
> This player won't play ads on Youtube.

@Andrews54757, thank you for implementing my suggestions.

I tested the new version 1.2.9 and it works great.

I also tested videos on sites other than youtube. Sometimes I feel like I have to manually hit enable the extension because it seems to be "sleeping" or not enabled. I mean if in youtube the extension is enabled, on other videos other than youtube it seems like the extension has disabled itself and I have to manually enable it.

If a site - for example, which does not have any clips - is it normal that the extension is not activated?

Here on github.com the extension is deactivated and I manually click it so it says "On". I don't know if this is normal.

Instead of some factor in the options (which is confusing and unclear which number means which factor and what resolution it equates to), isn't it easier/handier to manually describe what the user choice should be: 404p, 720p, 1080p, 2k, 4k , 8k?! I am attaching a picture of how it is implemented with the `Enhancer for Youtube` extension:

![ssss](https://github.com/Andrews54757/FastStream/assets/18578128/9a641fb6-c6f6-4b8b-a955-0d918aa847d0)


To skip ads (not see them) - does the extension actually use something like a **sponsor block**?

`Ungoogled Chromium v.120.0.6099.71 x64`, the extension is installed as a **crx** file according to the recommendations given here.

Thanks for the extension, still testing it.

**Comment by Andrews54757** [comment]
@Rusenche the extension will stay on/off on a per tab basis. you can setup auto enable URLs in settings to have it turn on automatically when entering a specific website.

The video quality multiplier setting cannot be a dropdown because some websites might use a quality that is not in the list. The current algorithm takes into account the size of the video on the page, and the resolution of your monitor to determine optimal playing quality. Qualities that are too high will result in a waste of computational and network resources (it takes forever to load 4k videos on some devices).

Basic sponsorblock support is implemented, but you will have to install Sponsorblock too to get those features. It doesn't support all features but it should be good enough for now.

**Comment by Rusenche** [comment]
@Andrews54757, thanks for the clarification.

I have a question and I have a suggestion.

Question: As far as I understand from the description here https://github.com/Andrews54757/FastStream/ the extension doesn't work with youtube livestreams and/or similar video sites?

Suggestion: After realizing that an automatic update is not possible as much as we want to use the function of downloading videos (`Chromium` + installing a `crx` file for the new version), and the presence of keyboard shortcuts, which for someone may be strictly individual , please consider the **option** to **import/export** individual **settings**. Such an option must be present. :}

**Comment by Andrews54757** [comment]
@Rusenche Yes, it doesn't work with livestreams.

With regards to importing/exporting settings, I've implemented something simple for you. https://github.com/Andrews54757/FastStream/commit/72f71b119ec2f6607246920e35bf2802c85fd92d

**Comment by Rusenche** [comment]
I personally checked the livestreams and it actually doesn't work, it freezes the video.

Just for my information - as far as I can tell - the extension practically downloads every single clip to the computer/phone to play each clip smoothly?

I just added version 1.2.10 and the option I wrote about in my previous post is now in place. I hope with this option all settings are saved?

@Andrews54757, thanks for the added changes.

**Comment by revunix** [comment]
> @Rusenche Qualities that are too high will result in a waste of computational and network resources (it takes forever to load 4k videos on some devices).

Would it be possible for you to add something like this anyway? I would also like to use it to watch 4K content. I also allow 4K as an extra option, which is deactivated by default.

**Comment by Andrews54757** [comment]
@revunix set quality multiplier factor to a high number to force FastStream to select the highest quality stream by default

**Comment by revunix** [comment]
@Andrews54757 Yeah but there is no option for 4k anyways. I can set the number to 10 and still get only 1080p.

**Comment by Andrews54757** [comment]
The website you visit gives FastStream a list of qualities that can be played. FastStream chooses an item on the list depending on your settings. It can't play something not on the list in the first place. if the stream doesn't have 4k video, then FastStream can't play 4k video.

**Comment by revunix** [comment]
@Andrews54757 but YouTube should work in 4K. In any case, it doesn't work.

**Comment by Andrews54757** [comment]
@revunix oh that, I am working on a fix. there seems to be an issue with Youtube.js or Dash.js that makes certain 4k videos unplayable due to bad content-ranges. See #70

**Comment by bandaid** [comment]
Predownload ought to be a slider and default to Mb/s, not MB/s. I believe the most suitable default should be 10 Mb/s. The slider could dynamically change from Kb/s, KB/s, Mb/s, then MB/s. I think it's important to remember users on slower connections, especially those in the rural areas. 1.5 Mb/s is still very standard.

https://github.com/Andrews54757/FastStream/discussions/69

**Comment by Andrews54757** [comment]
@bandaid The target download speed is a limiter, it doesn't guarantee that FastStream will be able to fetch content at that rate. The default speed is set to 300 MB/s so that throttling doesn't engage unless the user sets it. You can also set the speed in terms of other units, like Kb/s for example.

**Comment by bandaid** [comment]
> @bandaid The target download speed is a limiter, it doesn't guarantee that FastStream will be able to fetch content at that rate. The default speed is set to 300 MB/s so that throttling doesn't engage unless the user sets it. You can also set the speed in terms of other units, like Kb/s for example.

Therefore, it's advisable to set the maximum limit below 300 Mb/s and introduce the relevant terminology. Ideally, there should be a slider ranging from 0 Kb/s to a typical upper limit (likely more than a Gigabit) found in major cities. It's important to recognize that not every user of the extension understands the distinctions between Kb/KB and Mb/MB. Setting a cap at 300 MB/s could overwhelm the connection of users with a 1.5 Mb/s service, especially if the streaming provider supports faster download speeds.

**Comment by Andrews54757** [comment]
@bandaid Updated in https://github.com/Andrews54757/FastStream/commit/75d852a409b354e21ce6056b1ca761c37961ecd8

Now the limit will be infinite by default (no limiter), so that the user knows to reconfigure it to take effect. The default units have been changed to `Mbps` as well.

**Comment by Andrews54757** [comment]
Closing for now because issue is stale. Rewrite is still planned for the future.
